"""initial schema

Revision ID: 352c6a079e27
Revises: 
Create Date: 2026-03-02 13:03:16.588054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '352c6a079e27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('credibility_tier', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_knowledge_sources_category'), 'knowledge_sources', ['category'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('prompt_text', sa.String(length=50000), nullable=False),
    sa.Column('changelog', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('eval_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_name'), 'prompt_versions', ['prompt_name'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('hardiness_zones', sa.String(length=50), nullable=True),
    sa.Column('sun_requirement', sa.String(length=50), nullable=True),
    sa.Column('water_needs', sa.String(length=50), nullable=True),
    sa.Column('soil_ph_low', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('soil_ph_high', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('soil_type_preferred', sa.String(length=100), nullable=True),
    sa.Column('humidity_preference', sa.String(length=50), nullable=True),
    sa.Column('temp_min_f', sa.Integer(), nullable=True),
    sa.Column('temp_max_f', sa.Integer(), nullable=True),
    sa.Column('temp_ideal_low_f', sa.Integer(), nullable=True),
    sa.Column('temp_ideal_high_f', sa.Integer(), nullable=True),
    sa.Column('frost_tolerant', sa.Boolean(), nullable=False),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('mature_height', sa.String(length=50), nullable=True),
    sa.Column('mature_spread', sa.String(length=50), nullable=True),
    sa.Column('days_to_maturity', sa.Integer(), nullable=True),
    sa.Column('lifespan_type', sa.String(length=20), nullable=True),
    sa.Column('care_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_pests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('healthy_description', sa.String(length=1000), nullable=True),
    sa.Column('symptom_guide', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('antagonists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icon_emoji', sa.String(length=10), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('search_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_category'), 'species', ['category'], unique=False)
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('hardiness_zone', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('device_os', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_fcm_user_token')
    )
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_table('gardens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('hardiness_zone', sa.String(length=10), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('soil_ph_low', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('soil_ph_high', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('soil_drainage', sa.String(length=50), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gardens_user_id'), 'gardens', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_critical', sa.Boolean(), nullable=False),
    sa.Column('notification_advisory', sa.Boolean(), nullable=False),
    sa.Column('notification_info', sa.Boolean(), nullable=False),
    sa.Column('photo_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('photo_reminder_frequency', sa.String(length=20), nullable=False),
    sa.Column('privacy_default', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('light_type', sa.String(length=50), nullable=True),
    sa.Column('zone_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_garden_id'), 'zones', ['garden_id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('species_id', sa.Uuid(), nullable=True),
    sa.Column('custom_name', sa.String(length=200), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('location_detail', sa.String(length=50), nullable=True),
    sa.Column('container_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cover_photo_id', sa.Uuid(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photos.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_garden_id'), 'plants', ['garden_id'], unique=False)
    op.create_index(op.f('ix_plants_species_id'), 'plants', ['species_id'], unique=False)
    op.create_index(op.f('ix_plants_zone_id'), 'plants', ['zone_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('garden_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_pushed', sa.Boolean(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('original_url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_plant_id'), 'photos', ['plant_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('previous_photo_id', sa.Uuid(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('overall_health', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('hydration_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrient_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pest_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disease_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environmental_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('uncertainty_notes', sa.String(length=2000), nullable=True),
    sa.Column('prompt_version_used', sa.String(length=100), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_plant_id'), 'diagnoses', ['plant_id'], unique=False)
    op.create_table('ai_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('failure_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('input_summary', sa.String(length=2000), nullable=True),
    sa.Column('expected_output', sa.String(length=2000), nullable=True),
    sa.Column('actual_output', sa.String(length=2000), nullable=True),
    sa.Column('resolution', sa.String(length=2000), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_failures_failure_type'), 'ai_failures', ['failure_type'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('eval_type', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version_used', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_diagnosis_id'), 'eval_results', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_eval_results_eval_type'), 'eval_results', ['eval_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_results_eval_type'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_diagnosis_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_ai_failures_failure_type'), table_name='ai_failures')
    op.drop_table('ai_failures')
    op.drop_index(op.f('ix_diagnoses_plant_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_photos_plant_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_plants_zone_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_species_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_garden_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_zones_garden_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_gardens_user_id'), table_name='gardens')
    op.drop_table('gardens')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_index(op.f('ix_species_category'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_prompt_versions_prompt_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_knowledge_sources_category'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
