"""add grid fields to zones and plants

Revision ID: a3ad812036b4
Revises: 352c6a079e27
Create Date: 2026-03-03 16:05:57.360134
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ad812036b4'
down_revision: Union[str, None] = '352c6a079e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('grid_col', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('plants', sa.Column('grid_row', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'plants', 'photos', ['cover_photo_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('zones', sa.Column('grid_cols', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('zones', sa.Column('grid_rows', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'grid_rows')
    op.drop_column('zones', 'grid_cols')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'grid_row')
    op.drop_column('plants', 'grid_col')
    # ### end Alembic commands ###
